//algoritmo que calcula a média de um aluno com base em duas notas
Algoritmo "operadores"
   Var
      //definiçao das variáveis
      num1 : inteiro
      num2 : inteiro
      bol1 : logico
      bol2 : logico
      tex1 : caractere
      tex2 : caractere
      resultado : real
Inicio
   //pede as notas ao usuario e armazena nas variáveis
   num1 <- 10
   num2 <- 5
   bol1 <- verdadeiro
   bol2 <- falso
   tex1 <- "Bruna"
   tex2 <- "Moreira"
   resultado <- num1 + num2
   Fimalgoritmo

